### PR TITLE
Attempting parallel job

### PR DESCRIPTION
**Pull request by isuftin**
I updated the Travis file to see if it allows the jacoco build and the docker build to run in parallel to speed up the Travis building. The two builds don't depend on one another so there's no reason not to do that

### CODE REVIEW

**Comment by isuftin** [comment]
Travis got this error:

```
[ERROR] Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project aqcu-tss-report: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.)
```

What do you suppose that is, in relation to Coveralls?

**Comment by mhines-usgs** [comment]
@isuftin that doesn't matter, coveralls always fails on my fork

**Comment by isuftin** [comment]
Ok. So do try to merge this onto your fork and let's see if the Travis job passes since it will then be tested against your PR to master

**Comment by mhines-usgs** [comment]
pulled this into my PR

**Pull request merged**
